server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html index.htm;

    location ^~ /quanly/assets/ {
        alias /usr/share/nginx/html/assets/;
        try_files $uri =404;
    }

    location ^~ /assets/ {
        try_files $uri =404;
    }

    location = /quanly/icon.png {
        alias /usr/share/nginx/html/icon.png;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
