import { useEffect, useMemo, useState } from 'react';
import toast from 'react-hot-toast';
import api from '../../services/api';

const money = value => `${Number(value || 0).toLocaleString('vi-VN')} đ`;
export default function PricingPanel({ tours, canManage }) {
  const [tourId, setTourId] = useState('');
  const [form, setForm] = useState({ netServiceCostPerPerson: '', taxRate: 8, profitRate: 10, partnerCommissionPerDay: 160000 });
  const [result, setResult] = useState(null);
  const tour = tours.find(item => String(item._id) === String(tourId));
  useEffect(() => { if (!tour) return; setForm({ netServiceCostPerPerson: tour.pricing?.netServiceCostPerPerson || tour.estimatedCost || '', taxRate: Number(tour.pricing?.taxRate ?? .08) * 100, profitRate: Number(tour.pricing?.profitRate ?? .10) * 100, partnerCommissionPerDay: tour.pricing?.partnerCommissionPerDay ?? 160000 }); setResult(null); }, [tourId]);
  const preview = useMemo(() => { const net = Number(form.netServiceCostPerPerson) || 0; const tax = net * (Number(form.taxRate) || 0) / 100; const profit = net * (Number(form.profitRate) || 0) / 100; const commission = (Number(form.partnerCommissionPerDay) || 0) * (tour?.durationDays || 1); return { net, tax, profit, commission, price: Math.round(net + tax + profit + commission) }; }, [form, tour]);
  const save = async event => { event.preventDefault(); if (!tourId) return toast.error('Chọn tour trước'); try { const response = await api.put(`/tours/${tourId}/pricing`, { netServiceCostPerPerson: Number(form.netServiceCostPerPerson), taxRate: Number(form.taxRate) / 100, profitRate: Number(form.profitRate) / 100, partnerCommissionPerDay: Number(form.partnerCommissionPerDay) }); setResult(response.pricing); toast.success(response.message); } catch (error) { toast.error(error.message); } };
  return <section className="ops-panel"><h2>Cấu hình giá bán theo cấu phần</h2><p className="ops-form-note">Giá bán/khách = giá net dịch vụ + thuế + lợi nhuận + hoa hồng đại lý theo số ngày.</p><form className="ops-form" onSubmit={save}><label>Tour<select className="form-control" value={tourId} onChange={event => setTourId(event.target.value)} required><option value="">Chọn tour</option>{tours.map(item => <option key={item._id} value={item._id}>{item.code} · {item.name}</option>)}</select></label>{tour && <><div className="form-row"><label>Giá net dịch vụ/khách<input className="form-control" type="number" min="0" value={form.netServiceCostPerPerson} onChange={event => setForm({ ...form, netServiceCostPerPerson: event.target.value })} required /></label><label>Số ngày tour<input className="form-control" value={tour.durationDays || 1} readOnly /></label></div><div className="form-row-3"><label>Thuế (%)<input className="form-control" type="number" min="0" max="100" step="0.1" value={form.taxRate} onChange={event => setForm({ ...form, taxRate: event.target.value })} /></label><label>Lợi nhuận (%)<input className="form-control" type="number" min="0" max="100" step="0.1" value={form.profitRate} onChange={event => setForm({ ...form, profitRate: event.target.value })} /></label><label>Hoa hồng/ngày/khách<input className="form-control" type="number" min="0" value={form.partnerCommissionPerDay} onChange={event => setForm({ ...form, partnerCommissionPerDay: event.target.value })} /></label></div><div className="finance-summary"><div><small>Giá net</small><b>{money(preview.net)}</b></div><div><small>Thuế</small><b>{money(preview.tax)}</b></div><div><small>Lợi nhuận</small><b>{money(preview.profit)}</b></div><div><small>Hoa hồng {tour.durationDays || 1} ngày</small><b>{money(preview.commission)}</b></div><div><small>Giá bán đề xuất/khách</small><b className="profit-positive">{money(preview.price)}</b></div></div>{canManage && <button className="btn btn-primary">Lưu giá bán và đồng bộ giá Tour</button>}</>}</form>{result && <p className="ops-form-note">Đã lưu giá bán: <strong>{money(result.adultPrice)}</strong>/khách.</p>}</section>;
}
