import { CheckCircle2, Clock3, Plus, Trash2 } from 'lucide-react';

const weekDays = ['T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'CN'];

export default function RouteSchedulesPanel({ tours, vehicles, canManage, schedules, selectedTour, setSelectedTour, loading, form, setForm, editing, onNew, onEdit, onSubmit, onCancel }) {
  const update = (key, value) => setForm({ ...form, [key]: value });
  const updateStop = (index, key, value) => update('stops', form.stops.map((stop, itemIndex) => itemIndex === index ? { ...stop, [key]: value } : stop));
  const updateService = (index, key, value) => update('services', form.services.map((service, itemIndex) => itemIndex === index ? { ...service, [key]: value } : service));
  const toggleDay = (index, day) => updateService(index, 'daysOfWeek', form.services[index].daysOfWeek.includes(day) ? form.services[index].daysOfWeek.filter(item => item !== day) : [...form.services[index].daysOfWeek, day]);

  return <div className="route-schedules-layout">
    <section className="ops-panel route-schedule-list-panel">
      <div className="ops-panel-title"><div><h2>Lịch tuyến theo tour</h2><p>Tuyến mẫu để ghép hành trình nhiều chặng.</p></div></div>
      <label className="ops-label">Chọn tour<select className="form-control" value={selectedTour} onChange={event => { setSelectedTour(event.target.value); onCancel(); }}><option value="">Chọn tour cần cấu hình</option>{tours.map(tour => <option key={tour._id} value={tour._id}>{tour.code} · {tour.name}</option>)}</select></label>
      {loading && <p className="text-muted text-sm">Đang tải lịch tuyến...</p>}
      {!loading && schedules.map(schedule => <button type="button" className={`route-schedule-card ${editing?._id === schedule._id ? 'selected' : ''}`} key={schedule._id} onClick={() => onEdit(schedule)}><span><b>{schedule.code} · {schedule.name}</b><small>{schedule.stops?.length || 0} điểm · {schedule.services?.length || 0} chặng · đệm {schedule.transferMinutes} phút</small></span><em className={schedule.active ? 'active' : ''}>{schedule.active ? 'Đang dùng' : 'Tạm tắt'}</em></button>)}
      {!loading && selectedTour && !schedules.length && <div className="ops-empty route-schedule-empty"><Clock3 size={32} /><p>Tour chưa có lịch tuyến cố định.</p></div>}
      {!selectedTour && <p className="text-muted text-sm">Chọn tour để xem và quản lý lịch chạy.</p>}
      {canManage && selectedTour && <button type="button" className="btn btn-primary route-schedule-add" onClick={onNew}><Plus size={16} /> Thêm lịch tuyến</button>}
    </section>
    {selectedTour && canManage && <section className="ops-panel route-schedule-editor"><div className="ops-panel-title"><div><h2>{editing ? 'Sửa lịch tuyến' : 'Tạo lịch tuyến'}</h2><p>Thiết lập thứ chạy, chặng và xe mặc định.</p></div>{editing && <button type="button" className="btn btn-ghost btn-sm" onClick={onCancel}>Hủy sửa</button>}</div>
      <form className="ops-form" onSubmit={onSubmit}>
        <div className="form-row"><label>Mã tuyến *<input required className="form-control" value={form.code} onChange={event => update('code', event.target.value.toUpperCase())} /></label><label>Tên lịch tuyến *<input required className="form-control" value={form.name} onChange={event => update('name', event.target.value)} /></label></div>
        <div className="form-row"><label>Đệm chuyển xe (phút)<input type="number" min="0" className="form-control" value={form.transferMinutes} onChange={event => update('transferMinutes', event.target.value)} /></label><div className="route-schedule-checks"><label><input type="checkbox" checked={form.autoSuggest} onChange={event => update('autoSuggest', event.target.checked)} /> Tự động đề xuất</label><label><input type="checkbox" checked={form.active} onChange={event => update('active', event.target.checked)} /> Đang áp dụng</label></div></div>
        <div className="route-editor-block"><div className="stop-editor-title"><span>Điểm dừng theo thứ tự</span><button type="button" className="btn btn-secondary btn-sm" onClick={() => update('stops', [...form.stops, { code: '', name: '', address: '', sequence: form.stops.length }])}><Plus size={14} /> Thêm điểm</button></div>{form.stops.map((stop, index) => <div className="route-schedule-stop" key={`${index}-${stop.code}`}><strong>{index + 1}</strong><input required className="form-control" placeholder="Mã" value={stop.code} onChange={event => updateStop(index, 'code', event.target.value.toUpperCase())} /><input required className="form-control" placeholder="Tên điểm" value={stop.name} onChange={event => updateStop(index, 'name', event.target.value)} /><input className="form-control" placeholder="Địa chỉ" value={stop.address || ''} onChange={event => updateStop(index, 'address', event.target.value)} />{form.stops.length > 2 && <button type="button" className="btn btn-icon btn-ghost text-danger" onClick={() => update('stops', form.stops.filter((_, itemIndex) => itemIndex !== index))}><Trash2 size={15} /></button>}</div>)}</div>
        <div className="route-editor-block"><div className="stop-editor-title"><span>Chặng chạy cố định</span><button type="button" className="btn btn-secondary btn-sm" onClick={() => update('services', [...form.services, { code: `S${form.services.length + 1}`, originStopCode: form.stops[0]?.code || '', destinationStopCode: form.stops.at(-1)?.code || '', departureTime: '06:00', arrivalTime: '18:00', daysOfWeek: [1, 2, 3, 4, 5, 6, 0], defaultVehicle: '', active: true }])}><Plus size={14} /> Thêm chặng</button></div>{form.services.map((service, index) => <div className="route-service-row" key={`${index}-${service.code}`}><div className="form-row-3"><label>Mã chặng<input required className="form-control" value={service.code} onChange={event => updateService(index, 'code', event.target.value.toUpperCase())} /></label><label>Từ<select className="form-control" value={service.originStopCode} onChange={event => updateService(index, 'originStopCode', event.target.value)}>{form.stops.map(stop => <option key={stop.code} value={stop.code}>{stop.code} · {stop.name}</option>)}</select></label><label>Đến<select className="form-control" value={service.destinationStopCode} onChange={event => updateService(index, 'destinationStopCode', event.target.value)}>{form.stops.map(stop => <option key={stop.code} value={stop.code}>{stop.code} · {stop.name}</option>)}</select></label></div><div className="form-row-3"><label>Giờ đi<input required type="time" className="form-control" value={service.departureTime} onChange={event => updateService(index, 'departureTime', event.target.value)} /></label><label>Giờ đến<input required type="time" className="form-control" value={service.arrivalTime} onChange={event => updateService(index, 'arrivalTime', event.target.value)} /></label><label>Xe mặc định<select className="form-control" value={service.defaultVehicle || ''} onChange={event => updateService(index, 'defaultVehicle', event.target.value)}><option value="">Điều hành chọn sau</option>{vehicles.map(vehicle => <option key={vehicle._id} value={vehicle._id}>{vehicle.plateNumber} · {vehicle.seatCapacity} chỗ</option>)}</select></label></div><div className="route-days"><span>Chạy vào:</span>{weekDays.map((day, dayIndex) => { const value = dayIndex === 6 ? 0 : dayIndex + 1; return <button type="button" key={day} className={service.daysOfWeek.includes(value) ? 'active' : ''} onClick={() => toggleDay(index, value)}>{day}</button>; })}<label><input type="checkbox" checked={service.active !== false} onChange={event => updateService(index, 'active', event.target.checked)} /> Hoạt động</label>{form.services.length > 1 && <button type="button" className="btn btn-icon btn-ghost text-danger" onClick={() => update('services', form.services.filter((_, itemIndex) => itemIndex !== index))}><Trash2 size={15} /></button>}</div></div>)}</div>
        <div className="modal-footer"><button type="submit" className="btn btn-primary"><CheckCircle2 size={16} /> {editing ? 'Lưu lịch tuyến' : 'Tạo lịch tuyến'}</button></div>
      </form>
    </section>}
  </div>;
}
