"use client";
import { useEffect, useState } from "react";
import { appToast } from "./AppDialogProvider";
const API = (process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000") + "/api";
type Rule = { commission_type: string; commission_value: number; commission_children: boolean; commission_infants: boolean };
const emptyRule = (): Rule => ({ commission_type: "percentage", commission_value: 0, commission_children: true, commission_infants: false });
type Config = { own_commission: Rule; partner_overrides: (Rule & { partner_code: string })[]; net_cost_adult: number; net_cost_child: number; net_cost_infant: number; fixed_cost: number; tax_percent: number; profit_percent: number; commission_type: string; commission_value: number; commission_children: boolean; commission_infants: boolean; revenue_basis: string };
type Tour = { id: number; title: string; tour_code: string; config: Config };
export default function TourFinanceConfig({ onSaved }: { onSaved: () => void }) {
  const [tours, setTours] = useState<Tour[]>([]); const [selected, setSelected] = useState(""); const [config, setConfig] = useState<Config | null>(null); const [busy, setBusy] = useState(false); const [price, setPrice] = useState<number | null>(null);
  const headers = () => ({ "Content-Type": "application/json", Authorization: `Bearer ${localStorage.getItem("admin_token") || ""}` });
  useEffect(() => { fetch(`${API}/tour-operations/finance-config`, { headers: headers() }).then(async res => { const data = await res.json(); if (!res.ok) throw new Error(data.detail || "Không thể tải cấu hình"); setTours((data.tours || []).map((tour: Tour) => ({ ...tour, config: { ...tour.config, own_commission: tour.config.own_commission || emptyRule(), partner_overrides: tour.config.partner_overrides || [] } }))); }).catch(error => appToast(error.message)); }, []);
  const fields: [keyof Config, string][] = [["net_cost_adult", "Chi phí net/người lớn (đ)"], ["net_cost_child", "Chi phí net/trẻ em (đ)"], ["net_cost_infant", "Chi phí net/em bé (đ)"], ["fixed_cost", "Chi phí cố định/chuyến (đ)"], ["tax_percent", "Thuế trên net (%)"], ["profit_percent", "Lợi nhuận mục tiêu trên net (%)"], ["commission_value", "Hoa hồng đối tác mặc định (đ hoặc %)"]];
  return <details className="admin-finance-config"><summary>Cấu hình doanh thu, chi phí và hoa hồng theo tour</summary><form className="admin-finance-form" onSubmit={async event => { event.preventDefault(); if (!config || busy) return; setBusy(true); try { const response = await fetch(`${API}/tour-operations/finance-config/${selected}`, { method: "PUT", headers: headers(), body: JSON.stringify(config) }); const data = await response.json(); if (!response.ok) throw new Error(typeof data.detail === "string" ? data.detail : Array.isArray(data.detail) ? data.detail.map((item: { msg: string }) => item.msg.replace("Value error, ", "")).join("; ") : "Cấu hình không hợp lệ"); setConfig(data.config); setTours(current => current.map(tour => String(tour.id) === selected ? { ...tour, config: data.config } : tour)); setPrice(data.preview?.adult_price ?? null); appToast("Đã lưu cấu hình", "success"); onSaved(); } catch (error: unknown) { appToast(error instanceof Error ? error.message : "Không thể lưu cấu hình"); } finally { setBusy(false); } }}>
    <label>Tour<select required disabled={busy} value={selected} onChange={event => { setSelected(event.target.value); setConfig(tours.find(tour => String(tour.id) === event.target.value)?.config || null); setPrice(null); }}><option value="">Chọn tour</option>{tours.map(tour => <option key={tour.id} value={tour.id}>{tour.tour_code} · {tour.title}</option>)}</select></label>
    {config && <>{fields.map(([key, label]) => <label key={key}>{label}<input type="number" min="0" max={key === "tax_percent" || key === "profit_percent" ? 100 : key === "commission_value" && config.commission_type === "percentage" ? 99.99 : undefined} step="0.01" required value={Number(config[key])} onChange={event => setConfig({ ...config, [key]: Number(event.target.value) })} /></label>)}<label>Cách tính hoa hồng đối tác mặc định<select value={config.commission_type} onChange={event => setConfig({ ...config, commission_type: event.target.value, commission_value: 0 })}><option value="per_day">Theo ngày/khách</option><option value="per_guest">Theo khách</option><option value="percentage">% doanh thu sau giảm giá</option><option value="per_booking">Theo booking</option></select></label><label>Ghi nhận doanh thu<select value={config.revenue_basis} onChange={event => setConfig({ ...config, revenue_basis: event.target.value })}><option value="confirmed">Đơn đã xác nhận</option><option value="paid">Đơn đã xác nhận và thanh toán</option></select></label><label className="cms-check"><input type="checkbox" checked={config.commission_children} onChange={event => setConfig({ ...config, commission_children: event.target.checked })} />Tính hoa hồng trẻ em</label><label className="cms-check"><input type="checkbox" checked={config.commission_infants} onChange={event => setConfig({ ...config, commission_infants: event.target.checked })} />Tính hoa hồng em bé</label><fieldset style={{ gridColumn: "1 / -1" }} disabled={busy}><legend>Hoa hồng bên mình</legend><CommissionFields rule={config.own_commission} onChange={rule => setConfig({ ...config, own_commission: rule })} /><p>Áp dụng cho mọi booking được ghi nhận, kể cả khách đặt trực tiếp.</p></fieldset>
      <fieldset style={{ gridColumn: "1 / -1" }} disabled={busy}><legend>Hoa hồng riêng cho từng đối tác</legend>
        {config.partner_overrides.map((rule, index) => <fieldset key={index}><legend>Đối tác {index + 1}</legend><label>Mã đối tác trên booking<input required value={rule.partner_code} onChange={event => setConfig({ ...config, partner_overrides: config.partner_overrides.map((item, i) => i === index ? { ...item, partner_code: event.target.value } : item) })} /></label><CommissionFields rule={rule} onChange={value => setConfig({ ...config, partner_overrides: config.partner_overrides.map((item, i) => i === index ? { ...item, ...value } : item) })} /><button type="button" onClick={() => setConfig({ ...config, partner_overrides: config.partner_overrides.filter((_, i) => i !== index) })}>Xóa mức riêng</button></fieldset>)}
        <button type="button" onClick={() => setConfig({ ...config, partner_overrides: [...config.partner_overrides, { ...emptyRule(), partner_code: "" }] })}>Thêm đối tác</button><p>Mức riêng thay thế mức mặc định khi booking có mã tương ứng. Đặt mức 0 để không tính hoa hồng cho đối tác đó.</p>
      </fieldset><p className="admin-finance-note">Lợi nhuận = doanh thu − chi phí − hoa hồng. Hoa hồng đối tác áp dụng cho đơn có mã đại lý; hoa hồng bên mình là khoản riêng, cùng được trừ khỏi lợi nhuận. % tính trên toàn bộ giá trị booking sau giảm giá; tùy chọn trẻ em/em bé chỉ áp dụng cho mức theo khách hoặc ngày/khách. Giá đề xuất dùng mức đối tác mặc định, chưa phân bổ chi phí cố định/chuyến và hoa hồng/booking. Thay đổi cấu hình sẽ tính lại cả báo cáo các booking trước đây.</p><button type="submit" className="admin-btn-primary" disabled={busy}>{busy ? "Đang lưu…" : "Lưu cấu hình"}</button>{price !== null && <p>Giá người lớn đề xuất: <strong>{price.toLocaleString("vi-VN")} đ</strong></p>}</>}
  </form></details>;
}


function CommissionFields({ rule, onChange }: { rule: Rule; onChange: (rule: Rule) => void }) {
  return <div className="admin-finance-form">
    <label>Cách tính<select value={rule.commission_type} onChange={event => onChange({ ...rule, commission_type: event.target.value, commission_value: 0 })}>
      <option value="percentage">% giá trị booking sau giảm giá</option>
      <option value="per_guest">Số tiền cố định/khách</option>
      <option value="per_booking">Số tiền cố định/booking</option>
      <option value="per_day">Số tiền cố định/ngày/khách</option>
    </select></label>
    <label>Mức hoa hồng ({rule.commission_type === "percentage" ? "%" : "đ"})<input type="number" required min="0" max={rule.commission_type === "percentage" ? 99.99 : undefined} step="0.01" value={rule.commission_value} onChange={event => onChange({ ...rule, commission_value: Number(event.target.value) })} /></label>
    {(rule.commission_type === "per_guest" || rule.commission_type === "per_day") && <>
      <label className="cms-check"><input type="checkbox" checked={rule.commission_children} onChange={event => onChange({ ...rule, commission_children: event.target.checked })} />Tính cho trẻ em</label>
      <label className="cms-check"><input type="checkbox" checked={rule.commission_infants} onChange={event => onChange({ ...rule, commission_infants: event.target.checked })} />Tính cho em bé</label>
    </>}
  </div>;
}
