"use client";
import { useEffect, useState } from "react";
import { appToast } from "./AppDialogProvider";
const API = (process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000") + "/api";
type Config = { net_cost_adult: number; net_cost_child: number; net_cost_infant: number; fixed_cost: number; tax_percent: number; profit_percent: number; commission_type: string; commission_value: number; commission_children: boolean; commission_infants: boolean; revenue_basis: string };
type Tour = { id: number; title: string; tour_code: string; config: Config };
export default function TourFinanceConfig({ onSaved }: { onSaved: () => void }) {
  const [tours, setTours] = useState<Tour[]>([]); const [selected, setSelected] = useState(""); const [config, setConfig] = useState<Config | null>(null); const [busy, setBusy] = useState(false); const [price, setPrice] = useState<number | null>(null);
  const headers = () => ({ "Content-Type": "application/json", Authorization: `Bearer ${localStorage.getItem("admin_token") || ""}` });
  useEffect(() => { fetch(`${API}/tour-operations/finance-config`, { headers: headers() }).then(async res => { const data = await res.json(); if (!res.ok) throw new Error(data.detail || "Không thể tải cấu hình"); setTours(data.tours || []); }).catch(error => appToast(error.message)); }, []);
  const fields: [keyof Config, string][] = [["net_cost_adult", "Chi phí net/người lớn (đ)"], ["net_cost_child", "Chi phí net/trẻ em (đ)"], ["net_cost_infant", "Chi phí net/em bé (đ)"], ["fixed_cost", "Chi phí cố định/chuyến (đ)"], ["tax_percent", "Thuế trên net (%)"], ["profit_percent", "Lợi nhuận mục tiêu trên net (%)"], ["commission_value", "Mức hoa hồng (đ hoặc %)"]];
  return <details className="admin-finance-config"><summary>Cấu hình doanh thu, chi phí và hoa hồng theo tour</summary><form className="admin-finance-form" onSubmit={async event => { event.preventDefault(); if (!config || busy) return; setBusy(true); try { const response = await fetch(`${API}/tour-operations/finance-config/${selected}`, { method: "PUT", headers: headers(), body: JSON.stringify(config) }); const data = await response.json(); if (!response.ok) throw new Error(typeof data.detail === "string" ? data.detail : "Cấu hình không hợp lệ"); setPrice(data.preview?.adult_price ?? null); appToast("Đã lưu cấu hình", "success"); onSaved(); } catch (error: any) { appToast(error.message); } finally { setBusy(false); } }}>
    <label>Tour<select required value={selected} onChange={event => { setSelected(event.target.value); setConfig(tours.find(tour => String(tour.id) === event.target.value)?.config || null); setPrice(null); }}><option value="">Chọn tour</option>{tours.map(tour => <option key={tour.id} value={tour.id}>{tour.tour_code} · {tour.title}</option>)}</select></label>
    {config && <>{fields.map(([key, label]) => <label key={key}>{label}<input type="number" min="0" step="0.01" required value={Number(config[key])} onChange={event => setConfig({ ...config, [key]: Number(event.target.value) })} /></label>)}<label>Cách tính hoa hồng<select value={config.commission_type} onChange={event => setConfig({ ...config, commission_type: event.target.value })}><option value="per_day">Theo ngày/khách</option><option value="per_guest">Theo khách</option><option value="percentage">% doanh thu sau giảm giá</option><option value="per_booking">Theo booking</option></select></label><label>Ghi nhận doanh thu<select value={config.revenue_basis} onChange={event => setConfig({ ...config, revenue_basis: event.target.value })}><option value="confirmed">Đơn đã xác nhận</option><option value="paid">Đơn đã xác nhận và thanh toán</option></select></label><label className="cms-check"><input type="checkbox" checked={config.commission_children} onChange={event => setConfig({ ...config, commission_children: event.target.checked })} />Tính hoa hồng trẻ em</label><label className="cms-check"><input type="checkbox" checked={config.commission_infants} onChange={event => setConfig({ ...config, commission_infants: event.target.checked })} />Tính hoa hồng em bé</label><p className="admin-finance-note">Lợi nhuận = doanh thu − chi phí − hoa hồng. Hoa hồng áp dụng cho đơn có mã đại lý. Lợi nhuận mục tiêu dùng để đề xuất giá bán.</p><button type="submit" className="admin-btn-primary" disabled={busy}>{busy ? "Đang lưu…" : "Lưu cấu hình"}</button>{price !== null && <p>Giá người lớn đề xuất: <strong>{price.toLocaleString("vi-VN")} đ</strong></p>}</>}
  </form></details>;
}
